### ISSUE TITLE
WeChat's new sdk version is released~

### ISSUE THREAD

**Issue by muxinqi** [Adyen/adyen-wechatpay-ios#4]
**Is your feature request related to a problem? Please describe.**
This is not a problem. However, I noticed that the WeChat SDK has been released to 1.9.2 (as of November 26, 2021), and the version here is not currently up to date with the latest version.

I know there is no need to upgrade to the latest version for the time being in Adyen's project, so there is no incentive for this project to upgrade at this time either.

However, I appreciate the goal of this project, which is to save project developers using the Swift package manager as a dependency manager by wrapping the WeChat SDK (given that it's 2021, the WeChat SDK is still very cumbersome to introduce)

By the way, it took me a day and a half just to introduce the WeChat SDK into my project due to incomplete and outdated WeChat developer documentation.

**Describe the solution you'd like**
While my wish would be for the repository to be updated to the latest version and to provide the WeChat SDK package without the payment functionality, that would obviously add unnecessary development costs for you guys, plus it's actually a very niche requirement.

**Describe alternatives you've considered**
So I do hope that developers will share scripts or commands for making xcframework. Of course, I understand if this is a trade secret, but if so, I hope you can share some of your references for making xcframework

**Additional context**
I'm glad that the developers of `adyen-wechatpay-ios` have created such a tool to make it easy for later iOS developers to do chores other than development.

**Comment by mohammedDehairy** [comment]
Hi @muxinqi ,

Thanks for reaching out, we're glad that you find our repository useful :-).

 We will upgrade the WeChat .a library to the latest soon!.

 And Regarding sharing the source code and the recipe to generate an XCFramework, we thought when we created this repo that the source code would be of no interest to repo users, but if its interesting to you, we'll think of a way to share the knowledge and recipe.

Thanks again and I will update this thread once we find the optimal way to share the recipe, and when we upgrade the .a library to 1.9.2.

Mohamed

**Comment by mohammedDehairy** [comment]
Hi @muxinqi ,

We released `2.0.0-beta.1` with the latest `1.9.2` WeChat .a SDK, its still not available on CocoaPods, but its already available on SPM and Carthage, can you try it and let me know if its working with you?.

Mohamed

**Comment by muxinqi** [comment]
Hi @mohammedDehairy 

Your quick response and such amazing execution made me marvel!

First of all, I would like to say that `2.0.0-beta` is working fine in my project.

After introducing `adyen-wechatpay-ios`, I no longer have `-Objc` flag and 8 other redundant system framework introduction statements in my project configuration. This has made the project I maintain much easier to read and understand, and I believe this change is applicable to a wide range of application development engineers as well.

Needless to say, `adyen-wechatpay-ios` is a boon to engineers who want to keep their projects organized.

I am looking forward to the recipe for xcframework or any other related material(maybe a blog post about this repo) after experiencing the convenience of this project.

For many developers around me, one of the problems they usually face is that there are only two options for iOS SDKs from third-party vendors, and those are CocoaPods and manual introduction.

Now that it's almost 2022, Swift Package Manager is already a good dependency management tool. So many projects will be forced to use the latter method of introduction, which is the manual introduction method. 
This creates a problem, as many .a static libraries depend on some of the same system frameworks, which creates a maintenance disaster: it's hard to tell which static library depends on which system framework, even with a git operation log.

But now we have a very elegant solution, and this is what `adyen-wechatpay-ios` gives us.

After understanding how to make the xcframework, it'll be the time for me to make the WeChat SDK wrapper for the project I was maintaining. Yes, my current project does not use the WeChat payment feature so I can't bring in the `adyen-wechatpay-ios` project directly for now because it will cause the review team to reject my submission.

Looking forward to it, good luck!

Xinqi Mu
