### ISSUE TITLE
"Undefined symbol: _OBJC_CLASS_$_WXApi" error when I compile for simulator on an M1 mac

### ISSUE THREAD

**Issue by harryblam** [Adyen/adyen-wechatpay-ios#5]
**Describe the bug**
When building the dependency onto simulator on my M1 mac, i'm seeing the below error.
**Undefined symbol: _OBJC_CLASS_$_WXApi**

Stack trace:

> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_WXApi", referenced from:
>       objc-class-ref in CoreSocialLogin.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation) 
> 

When I comment out any references to the WXApi file however, it builds just fine. 

**Expected behavior**
I expect that I will be able to build onto a simulator on my M1 mac.

**Smartphone (please complete the following information):**
- Simulator, iOS 15, iPhone 12 Pro, M1 mac

**Additional context**
Unsure if it is the cause or not, but we have broken our app into modules (local swift packages). This is dependency is being pulled in from one of our local swift packages Package.swift files, and not from the Xcode project file itself.

**Comment by descorp** [comment]
Hey @harryblam 

Unfortunately WeChat lib does not support `arm64`, even the latest version 1.9.2.

**Comment by harryblam** [comment]
Hi @descorp , thanks for the quick reply!

That really sucks from their side. Do you think that there could be a way around this by recompiling the WeChat framework from scratch and including the arm64 binaries in the Adyen XCFramework package?

**Comment by descorp** [comment]
Hey @harryblam 

Seems like we can ignore WeChat by using `arch(arm64)`.
Will investigate further. 

```
#if arch(arm64)
        return false
    #else
        WXApi.registerApp("", universalLink: "")
        return WXApi.isWXAppInstalled() && WXApi.isWXAppSupport()
#endif
```

**Comment by harryblam** [comment]
Nice find! This could indeed help for development purposes, however this wouldn't work in production though, as arm64 is the current iOS CPU architecture (used since the iPhone 5S) right?

**Comment by harryblam** [comment]
The below issue ticket links to an article that says that we could set the project `VALID_ARCHS` to exclude arm64. Could that help? 
https://developers.weixin.qq.com/community/develop/doc/0008a0b0f90e80a7520b4c0055b400

**Comment by descorp** [comment]
Hey @harryblam 

Indeed.. We are looking towards `#if targetEnvironment(simulator)` now

**Comment by harryblam** [comment]
Thanks @descorp , this is a nice workaround ☝️

**Comment by descorp** [comment]
I'll pin it :)
